// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkdGFgGj1YiD_Ssoh2OH_jzQnb4_icM9w',
    appId: '1:185673802595:web:08fa2971bd494fe39e6956',
    messagingSenderId: '185673802595',
    projectId: 'instaclone-e672f',
    authDomain: 'instaclone-e672f.firebaseapp.com',
    databaseURL: 'https://instaclone-e672f-default-rtdb.firebaseio.com',
    storageBucket: 'instaclone-e672f.firebasestorage.app',
    measurementId: 'G-5YW8QJ9V7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARPvLrFPlqouiTW1gimIh3NnBd59uxmtI',
    appId: '1:185673802595:android:06ace65a7dc4d7919e6956',
    messagingSenderId: '185673802595',
    projectId: 'instaclone-e672f',
    databaseURL: 'https://instaclone-e672f-default-rtdb.firebaseio.com',
    storageBucket: 'instaclone-e672f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_1E9GfhjceVmliXy4eycwqYjhvQZqcc',
    appId: '1:185673802595:ios:e4c2916ad33cb7669e6956',
    messagingSenderId: '185673802595',
    projectId: 'instaclone-e672f',
    databaseURL: 'https://instaclone-e672f-default-rtdb.firebaseio.com',
    storageBucket: 'instaclone-e672f.firebasestorage.app',
    iosBundleId: 'com.example.instaclone',
  );

}